/**
 * Data for the landing-page route planner. Generated by scripts/landing-map/build.mjs; do not edit by hand.
 * Homes and the school sit on real streets around Aspire Park, Doha (map data © OpenStreetMap contributors, ODbL).
 * The K-Means history is a real run from deliberately poor starting centres, and each route follows the road network,
 * one-way streets included, from the first stop to the school.
 */

export interface Point {
  x: number
  y: number
}

export interface KMeansStep {
  centroids: Point[]
  assignment: number[]
}

/** Map units; the base map images use the same 540 x 400 frame. */
export const MAP_WIDTH = 540
export const MAP_HEIGHT = 400
/** Real-world metres per map unit, for the scale bar. */
export const METERS_PER_UNIT = 5.6

/** Base map images (content-hashed file names). */
export const MAP_IMAGES = {"light":"/assets/maps/aspire-light-c0dda3e0.webp","dark":"/assets/maps/aspire-dark-f5ca1098.webp"} as const

export const SCHOOL: Point = {"x":259.9,"y":240.6}
export const CLUSTER_COUNT = 3

export const HOMES: Point[] = [{"x":47.5,"y":236.4},{"x":48.4,"y":217.2},{"x":97.4,"y":245.4},{"x":77.2,"y":286.2},{"x":32.4,"y":286.1},{"x":34.6,"y":253.6},{"x":47.7,"y":275.6},{"x":78,"y":255.4},{"x":33.5,"y":234.7},{"x":315,"y":19.5},{"x":305,"y":80.2},{"x":317.8,"y":78.2},{"x":327.6,"y":27.5},{"x":295.5,"y":27.4},{"x":300.5,"y":69},{"x":265.3,"y":37.8},{"x":258.7,"y":54},{"x":302,"y":15},{"x":517.5,"y":215.4},{"x":498.8,"y":158.4},{"x":505.9,"y":199.9},{"x":518.3,"y":173.2},{"x":499.1,"y":146.6},{"x":513.7,"y":185.5},{"x":500.6,"y":183.2},{"x":510.5,"y":160.1},{"x":530.5,"y":185.8}]

export const KMEANS_HISTORY: KMeansStep[] = [{"centroids":[{"x":200,"y":110},{"x":250,"y":210},{"x":330,"y":290}],"assignment":[0,0,1,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2]},{"centroids":[{"x":219.3,"y":103.9},{"x":66.5,"y":269.7},{"x":510.5,"y":178.7}],"assignment":[1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2]},{"centroids":[{"x":298.6,"y":45.4},{"x":55.2,"y":254.5},{"x":510.5,"y":178.7}],"assignment":[1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2]}]

export const FINAL_SNAPSHOT: KMeansStep = {"centroids":[{"x":298.6,"y":45.4},{"x":55.2,"y":254.5},{"x":510.5,"y":178.7}],"assignment":[1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,2,2,2,2,2,2,2,2,2]}
export const FINAL_ASSIGNMENT = FINAL_SNAPSHOT.assignment

/** Road-following route for each bus, from its first stop to the school. */
export const ROUTE_PATHS: string[] = [
  "M327.6 27.5 L332.6 25.3 L336 33.4 L326.4 37.8 L325 37.4 L323.9 36.2 L316.8 20.6 L315 19.5 L306.7 23.1 L313.2 38.1 L303 42.3 L296.9 28.8 L295.5 27.4 L265.3 37.8 L263.7 39 L263 40.3 L264 43.9 L265.2 45.5 L269.7 47.8 L266.2 57.7 L261.7 55.9 L258.7 54 L261.7 55.9 L276 61.2 L300.5 69 L295.8 67.9 L293.1 77 L300.4 79.4 L305 80.2 L311.7 79.7 L317.8 78.2 L311.7 79.7 L305 80.2 L300.4 79.4 L293.1 77 L295.8 67.9 L266.2 57.7 L261.7 55.9 L258.7 54 L255.6 50 L250.3 37.7 L250.7 33.9 L253.4 31.3 L298.9 14.2 L302 15 L303.3 16.1 L306.7 23.1 L313.2 38.1 L283 50 L280.9 50.5 L276.8 49.9 L269.7 47.8 L266.2 57.7 L276 61.2 L264.9 96.1 L253.7 93.6 L248.1 93.1 L216 92.9 L216.7 125.9 L216.9 238.3 L218.7 240.3 L259.9 240.6",
  "M77.2 286.2 L77.9 284.7 L78 255.4 L77 254.1 L75.2 253.7 L34.6 253.6 L33.1 254.4 L32.7 255.8 L31.9 285.3 L32.4 286.1 L47.7 286.3 L47.7 275.6 L47.8 253.4 L38.4 253.3 L38.4 245.1 L24.3 245.3 L24.8 229.3 L33.7 229.1 L33.5 234.7 L34.9 236.2 L47.5 236.4 L48 235.6 L47.9 229.6 L47.4 229 L42.5 228.6 L41.5 227.6 L41.6 219.7 L42.6 218.7 L47.1 218.8 L47.8 218.5 L48.4 217.2 L48.6 206 L56.8 206.2 L55.5 244.9 L95.4 244.9 L97.4 245.4 L100.4 246.8 L101.7 246.3 L102.3 244.8 L100.7 239.6 L100.3 235.6 L100.2 211.1 L102.4 205.7 L100 199.6 L100.5 157.4 L77.1 157.5 L77.3 148.7 L70.5 148.6 L68.8 148.3 L67.9 147.1 L68 137.2 L59.2 137.2 L59.2 130.9 L60.6 126.2 L64.7 123.5 L91.1 115.2 L109.9 110.8 L111.9 109.7 L114.1 106.1 L115.2 102.5 L115.2 98.4 L116.3 96 L117.4 83 L118.6 78.5 L121.9 73.7 L126.2 70.4 L135.5 66.9 L206.6 47.4 L212.4 47.8 L214.5 49 L215.9 50.9 L216.9 238.3 L218.7 240.3 L259.9 240.6",
  "M517.5 215.4 L506.4 219.8 L499.6 200.8 L492.9 189 L493.8 186.3 L500.6 183.2 L509.4 179.4 L512.1 186.2 L513.7 185.5 L512.1 186.2 L509.4 179.4 L519.3 174.9 L518.3 173.2 L510.5 160.1 L509.6 160 L503.7 162.7 L503.3 163.3 L511.7 178.3 L498.5 184.1 L504.2 198.9 L505.9 199.9 L504.2 198.9 L498.5 184.1 L509.4 179.4 L514.7 192.2 L530.5 185.8 L514.7 192.2 L509.4 179.4 L493.8 186.3 L491 185.8 L487.5 182.1 L485.4 181.6 L476.3 171 L475.4 166.8 L473.6 164.5 L474.1 162.3 L486.2 149.8 L495.1 157.9 L496.9 158.7 L498.8 158.4 L509.3 153.6 L505.2 144.1 L499.1 146.6 L505.2 144.1 L509.3 153.6 L498.8 158.4 L496.9 158.7 L495.1 157.9 L486.2 149.8 L474.1 162.3 L472.2 163.2 L468.2 161.1 L465.7 160.8 L458.1 155 L447.2 148.5 L439.6 144.7 L408.5 133.9 L406.4 132.6 L402.7 127.1 L399.1 125 L396.4 124.8 L394.1 125.6 L392.1 127 L390.5 129.3 L385.4 131.2 L378.7 130.9 L371.8 129.9 L357.1 125.9 L264.9 96.1 L259.2 94.7 L248.1 93.1 L216 92.9 L216.7 125.9 L216.9 238.3 L218.7 240.3 L259.9 240.6"
]

/** First stop of each route, where its driver label sits. */
export const ROUTE_STARTS: Point[] = [{"x":327.6,"y":27.5},{"x":77.2,"y":286.2},{"x":517.5,"y":215.4}]
